export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';

export const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_ERROR = 'UPDATE_USER_INFO_ERROR';

export const GET_USER_PROPERTY_REQUEST = 'GET_USER_PROPERTY_REQUEST';
export const GET_USER_PROPERTY_SUCCESS = 'GET_USER_PROPERTY_SUCCESS';
export const GET_USER_PROPERTY_ERROR = 'GET_USER_PROPERTY_ERROR';

export const UPDATE_PROPERTY_INFO_REQUEST = 'UPDATE_PROPERTY_INFO_REQUEST';
export const UPDATE_PROPERTY_INFO_SUCCESS = 'UPDATE_PROPERTY_INFO_SUCCESS';
export const UPDATE_PROPERTY_INFO_ERROR = 'UPDATE_PROPERTY_INFO_ERROR';

export const GET_ALL_TRANSACTION_DETAILS_REQUEST =
  'GET_ALL_TRANSACTION_DETAILS_REQUEST';
export const GET_ALL_TRANSACTION_DETAILS_SUCCESS =
  'GET_ALL_TRANSACTION_DETAILS_SUCCESS';
export const GET_ALL_TRANSACTION_DETAILS_ERROR =
  'GET_ALL_TRANSACTION_DETAILS_ERROR';

export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';

export const UPDATE_PARTY_REQUEST = 'UPDATE_PARTY_REQUEST';
export const UPDATE_PARTY_SUCCESS = 'UPDATE_PARTY_SUCCESS';
export const UPDATE_PARTY_ERROR = 'UPDATE_PARTY_ERROR';

export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_ERROR = 'GET_NOTIFICATION_ERROR';

export const GET_CASHFREE_USER_TOKEN_REQUEST =
  'GET_CASHFREE_USER_TOKEN_REQUEST';
export const GET_CASHFREE_USER_TOKEN_SUCCESS =
  'GET_CASHFREE_USER_TOKEN_SUCCESS';
export const GET_CASHFREE_USER_TOKEN_ERROR = 'GET_CASHFREE_USER_TOKEN_ERROR';

export const ADD_BENEFICIARY_REQUEST = 'ADD_BENEFICIARY_REQUEST';
export const ADD_BENEFICIARY_SUCCESS = 'ADD_BENEFICIARY_SUCCESS';
export const ADD_BENEFICIARY_ERROR = 'ADD_BENEFICIARY_ERROR';

export const PAYOUT_REQUEST = 'PAYOUT_REQUEST';
export const PAYOUT_SUCCESS = 'PAYOUT_SUCCESS';
export const PAYOUT_ERROR = 'PAYOUT_ERROR';

export const RESET_GENERIC = 'RESET_GENERIC';

export const ADD_VENDOR_REQUEST = 'ADD_VENDOR_REQUEST';
export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS';
export const ADD_VENDOR_ERROR = 'ADD_VENDOR_ERROR';

export const GET_VENDOR_REQUEST = 'GET_VENDOR_REQUEST';
export const GET_VENDOR_SUCCESS = 'GET_VENDOR_SUCCESS';
export const GET_VENDOR_ERROR = 'GET_VENDOR_ERROR';

export const GET_CATEGORY_VENDOR_REQUEST = 'GET_CATEGORY_VENDOR_REQUEST';
export const GET_CATEGORY_VENDOR_SUCCESS = 'GET_CATEGORY_VENDOR_SUCCESS';
export const GET_CATEGORY_VENDOR_ERROR = 'GET_CATEGORY_VENDOR_ERROR';

export const GET_SELECTED_VENDOR_REQUEST = 'GET_SELECTED_VENDOR_REQUEST';
export const GET_SELECTED_VENDOR_SUCCESS = 'GET_SELECTED_VENDOR_SUCCESS';
export const GET_SELECTED_VENDOR_ERROR = 'GET_SELECTED_VENDOR_ERROR';

export const DELETE_VENDOR_REQUEST = 'DELETE_VENDOR_REQUEST';
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const DELETE_VENDOR_ERROR = 'DELETE_VENDOR_ERROR';

export const ADD_TO_MYSERVICE_REQUEST = 'ADD_TO_MYSERVICE_REQUEST';
export const ADD_TO_MYSERVICE_SUCCESS = 'ADD_TO_MYSERVICE_SUCCESS';
export const ADD_TO_MYSERVICE_ERROR = 'ADD_TO_MYSERVICE_ERROR';

export const SET_NAVIGATION_TITLE = 'SET_NAVIGATION_TITLE';

export const GET_BENE_ID_REQUEST = 'GET_BENE_ID_REQUEST';
export const GET_BENE_ID_SUCCESS = 'GET_BENE_ID_SUCCESS';
export const GET_BENE_ID_ERROR = 'GET_BENE_ID_ERROR';
export const RESET_BENE_ID = 'RESET_BENE_ID';
